### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mpintar** [AlexSabourinDev/software-development-resources#3]
It might be a good idea when this list starts to get a bit longer to start breaking up the list a bit more.

**Comment by AlexSabourinDev** [comment]
Agreed, I'm open to suggestions on categories

**Comment by mpintar** [comment]
I have a bit more time tonight hopefully. I will add more links and start to categorize them and throw up a PR with those changes

**Comment by AlexSabourinDev** [comment]
Great, thanks!

**Comment by AlexSabourinDev** [comment]
Made some rough categories :)

**Comment by mpintar** [comment]
Sweet!
